### ISSUE TITLE
mobile menu/search bug - Blackberry Z10

### ISSUE THREAD

**Issue by pcwsmith** [wet-boew/GCWeb#901] opened 2015-02-13 22:09 UTC
user testing participant could not use the mobile menu/search button, tried repeatedly. See video clip: http://youtu.be/USSkHvDnTxc

h/t @neoinsight

**Comment by LaurentGoderre** [comment] 2015-02-13 22:21
As you can notice, even the carousel navigation button are not loading which indicates a JavaScript failure (either not loaded or a critical issue occured during its execution).

I have seen a similar issue on my Z10 when the phone is low on physical storage it gives a quote exception which halts the execution of WET. Usually, clearing the cache and restarting the phone fixes this issue.

That being said, @neoinsight I could come over to look at this particular device using the devs tools to confirm that this is what is occurring.

**Comment by LaurentGoderre** [comment] 2015-02-13 22:22
Please note that other browser can be affected by a similar situation since a quote exception is part of the HTML5 spec

**Comment by neoinsight** [comment] 2015-02-13 22:24
@LaurentGoderre the participant who used the device was only here for an hour. I did note that she was using the native Blackberry browser. The weird thing is that a lot of the form validation fields worked just fine - it was only the menu button that totally didn't work. She said it's happened once or twice before on other sites.

**Comment by neoinsight** [comment] 2015-02-13 22:26
I'll be providing a video of her entire session to @pcwsmith  (don't want to put the full hour onto Youtube).  The second participant had some weird stuff too on her iPhone.That's coming soon in a separate issue.

**Comment by LaurentGoderre** [comment] 2015-02-13 22:26
It is possible that this issue is getting fixed in the new OS (I have the leaked version and do not experience this)

**Comment by LaurentGoderre** [comment] 2015-02-13 22:28
Here is a screenshot from my Z10 showing that it is working 
![img_20150213_172530](https://cloud.githubusercontent.com/assets/1090826/6196339/a3337858-b3a5-11e4-9b9b-b438e752b31d.png)
![img_20150213_172530](https://cloud.githubusercontent.com/assets/1090826/6196342/ab9758e8-b3a5-11e4-8691-2652f1a5ed55.png)

**Comment by LaurentGoderre** [comment] 2015-02-13 22:31
@neoinsight Blackberry phones, like many phones nowadays, have very good developers tools that can tell you where such errors are coming from (you just need to enale the option, connect the phone via a USB cable to your laptop and access the devtools via your Google Chrome)

**Comment by neoinsight** [comment] 2015-02-13 22:45
Hmm, I only pay participants for an hour, and have a lot to get through. I don't think that's something that would be possible within a usability session. I just can't do QA. I am collecting people's browser version numbers this time if they are on a laptop, that's as far as I can go. 

Don't know if this helps, but also saw this occur on her session - the whole time she was interacting with the CIC Come to Canada pages, the menu did not show the search icon with the menu icon. Oh, well, my iPhone does that too. Maybe I should report that separately to CIC? 
![blackberry z10 cic menu without search icon](https://cloud.githubusercontent.com/assets/1855584/6196617/faf13e5c-b3a7-11e4-8812-54144d263770.png)

**Comment by LaurentGoderre** [comment] 2015-02-14 02:40
That might be because they are using an older code base

**Comment by RobJohnston** [comment] 2015-02-17 15:23
Just checked and CIC is currently on 4.0.9.

**Comment by LaurentGoderre** [comment] 2015-02-17 15:31
That's weird...I do not get that behavior on a desktop in mobile view

**Comment by neoinsight** [comment] 2015-02-17 15:50
I do - it's in the Come to Canada application. http://onlineservices-servicesenligne.cic.gc.ca/eapp/eapp.do

**Comment by RobJohnston** [comment] 2015-02-17 15:50
I think the missing search is CIC's doing.  If you go to http://www.cic.gc.ca/ctc-vac/getting-started.asp and click the "Check your eligibility" button then you get into the "Online Services" section like in the last screenshot.  Even in desktop mode the search is not present.

BTW, I've got a personal Blackberry Z30 that I can use to troubleshoot in evening hours.

**Comment by LaurentGoderre** [comment] 2015-02-17 15:55
OOOh but the search is not present on that page in desktop view. It was probably taken out to prevent someone to navigate away midway through the process

**Comment by LaurentGoderre** [comment] 2015-02-17 15:56
It's weird though because this behavior is not documented anywhere....there probably should be an example of this somewhere

**Comment by neoinsight** [comment] 2015-02-17 16:03
That's tricky - search is gone but the menu to nav away is not. Confusing.  Actually, the menu DID cause problems too because they selected something (to leave) and then got this wickedly confusing Do you really want to exit, cancel/continue page. That whole model of leaving an application needs work.

**Comment by LaurentGoderre** [comment] 2015-02-17 16:06
Oh I agree!

**Comment by RobJohnston** [comment] 2015-02-17 16:10
And they're talking about that in [#6438] (https://github.com/wet-boew/wet-boew/issues/6438).

**Comment by LaurentGoderre** [comment] 2015-02-18 19:04
I reproduced by filling my Z10 to capacity and am testing some fixes

**Comment by LaurentGoderre** [comment] 2015-02-19 03:05
The original issue was fixed upstream. The working examples are working as intended now

**Closed by LaurentGoderre** 2015-02-19 03:05 UTC
