### ISSUE TITLE
Canada.ca - Links in header using basic HTML mode are broken

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/GCWeb#1163] opened 2016-08-31 15:20 UTC
For the Canada.ca site, all the links in the header are broken in basic HTML mode:
https://www.canada.ca/en.html?wbdisable=true

This is not the way WET works demo site:
http://wet-boew.github.io/themes-dist/GCWeb/content-en.html?=undefined&wbdisable=true

For Travel and tourism (again, in basic HTML mode), the link to "Jobs" gets a 404.
https://travel.gc.ca/?wbdisable=true

**Comment by shawnthompson** [comment] 2016-11-10 14:13
@RobJohnston [GCWeb sample pages](http://wet-boew.github.io/themes-dist/GCWeb/index-en.html?wbdisable=true) are working as intended with wb-disable set to true.

@masterbee / @MaximMartel Canada.ca isn't using AJAX to call the menu but GCWeb so the links in the main menu should be fix to point to the proper link or maybe it should be using the CDN menu.

As for [travel](https://travel.gc.ca/?wbdisable=true), they have the wrong source code in the link. They should be using the same links as GCWeb

**Comment by duboisp** [comment] 2017-05-26 13:46
This issue is fixed with the WET 4.0.25 release

See:`
* http://wet-boew.github.io/themes-dist/GCWeb/index-en.html?wbdisable=true
* http://wet-boew.github.io/themes-dist/GCWeb/index-en.html?wbdisable=false

**Comment by RobJohnston** [comment] 2017-05-26 13:53
It always worked correctly on the WET site, but not the actual Canada.ca site:  https://www.canada.ca/en.html?wbdisable=true.  

I thought that reporting it here might be the quickest way to get somebody's attention.  Alas, I was mistaken.

**Comment by duboisp** [comment] 2017-05-26 14:01
FYI - The canada.ca english home page currently run with WET 4.0.23

I think there is a different process that do not rely on github to report formal issue related to Canada.ca and with his web managed service. cc/ @MaximMartel

**Comment by EricDunsworth** [comment] 2017-06-05 20:26
FWIW, I've opened a request for this in Principal Publisher's ticketing system for Canada.ca. Also referred to this issue and #1254.

@lucas-hay FYI.

**Closed** 2017-12-07 14:00 UTC
