### ISSUE TITLE
Accessibility/Usability: Add close buttons to overlays

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#1156] opened 2016-07-26 01:26 UTC
Attention @shawnthompson -  @touficS -@pcwsmith - @dk-tbs

**THE CLOSE BUTTON**

@matyeo recommended adding a Close button to the side-panel overlay after usability testing of some alternatives. With your coding help, I am currently testing a Close button on a 60% width right-panel overlay. We started the testing with some iPhones VoiceOver users. You can see the test example here - click the 'How to find browser version' link on this page: http://thomas.gohard.me/web-form-validation-test/index-en.html

**Recommendation**: Based their experience with the overlay, and the experience of the sighted participants, adding a close button to the bottom of the Left and Right panel, and Centred Popup Lightbox overlays would be a usability and accessibility improvement.

Both iPhone VoiceOver participants heard and used the Close button in the side overlay panel (although it wasn't without problems, but they will be posted as a separate issue). In contrast, watch the difficulty that the participant has on the Passport Service Location page with the Centred Popup Lightbox that does NOT have a Close button: 

iPhone Voice Over participant on Passport Service Location page - struggles with Centred Popup Lightbox overlay - no Close button, tries to use Back button:
https://www.youtube.com/watch?v=Wmo0pAbL47M

Thoughts? Not sure who edits the WET demos these days...

**Comment by hsrudnicki** [comment] 2016-08-30 20:22
Please update the status of this whether this can be closed as resolved or otherwise? Thx

**Comment by neoinsight** [comment] 2016-08-30 20:49
Not done, needs to be done. Leave open until someone self assigns please - our testing results suggest overlays can be a great solution for many 'some people need more information' situations.

**Comment by kodecount** [comment] 2017-02-21 15:51
It makes sense the back button doesn't work since it not a new webpage. I prefer the overlay that has a close button over the 'X' when I was developing an application for accessibility.

**Comment by neoinsight** [comment] 2017-02-21 16:06
@kodecount Based on the sighted and screenreader participant experiences, we think all overlays should have a close button on the x AND at the bottom of the content. Notice above the screenreader struggling with the Centred Lightbox. 

Also, the problem with the Centred overlay is that non-screenreader participants couldn't see the form anymore - the context that they were seeking to understand by clicking on the overlay. The right overlay worked much better for that purpose.

**Comment by kodecount** [comment] 2017-02-21 16:18
Yes I agreed. I was more so referring to the centered popup due to having a button. Currently the button isn't generated and is manually added to that example.

**Comment by neoinsight** [comment] 2017-02-21 16:24
Ah I see. Yes, what I'm hoping for here is that the X stays where it is -no changes, but that the Close button is generated for all overlays - doesn't have to be manually added.

**Comment by kodecount** [comment] 2017-02-21 16:26
Generating the closing button be simple actually. Standard location would be in the modal footer.

**Comment by kodecount** [comment] 2017-02-21 17:49
Did some more testing:

- Top and bottom overlay bar should be excluded due to it limited retail space (button shouldn't be hard to hit)
- Middle screen popups/overlays use light box (I can investigate, may be slight more complicated).
- Full screen overlay has issue with button (mainly the one without a header).

As for left and right bar they should be straight forward I can do up a concept.

**Comment by neoinsight** [comment] 2017-02-21 17:54
Oh yes, top and bottom bars weren't included. Have not tested them with any participants - if you know of any in use, would love a URL so could include in next test. 
Thanks
Copying @toufics and @RubyDo since the overlay for help on forms first came from them.

**Comment by kodecount** [comment] 2017-02-21 17:55
I can upload a copy to my site after work (government network block access to outside IP calls).

I'll also update this comment with a branch to my code when I get a chance.

**Comment by kodecount** [comment] 2017-02-21 18:33
No I don't know of any top and bottom bar (I did see it some where (it was an intranet site so no link)).

But I can create a text case with the left and right modals if you want (with the new buttons):

Left Panel:
![left-panel](https://cloud.githubusercontent.com/assets/23484460/23178926/8e41bb9c-f842-11e6-8926-c9a51488f0c5.jpg)

Right Panel:
![right-panel](https://cloud.githubusercontent.com/assets/23484460/23178940/98e523d6-f842-11e6-8328-138d291a3a47.jpg)

This commit would auto add the close button (even if no footer exist): https://github.com/kodecount/wet-boew/commit/cd965648ce33b6cdec63e65b6e1b016d2a0de058

**Comment by kodecount** [comment] 2017-02-21 20:11
Centred popup (Lightbox):
![modal-center](https://cloud.githubusercontent.com/assets/23484460/23182824/46d7dd46-f850-11e6-90cc-3684a1fbbc0b.jpg)

Centred popup - Modal (Lightbox + Modal):
![modal-center-no-x](https://cloud.githubusercontent.com/assets/23484460/23182831/4d1a2d8a-f850-11e6-95d8-6c2f2d3ee25f.jpg)

This commit would auto add the close button (even if no footer exist): https://github.com/kodecount/wet-boew/commit/3474d83d0f95cdda5b6070c1a82a520f83df9f05

I've added the code to WET directly (my forked version) I think personally that it shouldn't be just changed in this theme, but If any one is against it I could added it to this project.

**Comment by neoinsight** [comment] 2017-02-21 20:25
Looks good @kodecount! 
Agree re WET vs theme. 
Any reason you've right-aligned button in centred rather than left? We understand low-vision users track along the left of the screen so best for buttons and labels to be in view for them.

**Comment by kodecount** [comment] 2017-02-21 20:26
Just visual appeal commonly on the right.

**Comment by kodecount** [comment] 2017-02-21 20:35
Also I think the only overlays that would be a issue adding the button is Middle and Full Screen. They should probably have one. It mostly the 'hidden-hd' that causes an issue. May look into.

**Comment by kodecount** [comment] 2017-02-21 23:41
It was what is commonly done visual, but it a simple change in the code.

**Comment by kodecount** [comment] 2017-02-22 03:18
Hey you can now see a live example of the code above here: http://kodecount.ca/demos/overlays/

**Comment by nschonni** [comment] 2017-02-22 04:13
Not saying any of the above doesn't do this, but also think about low vision people too. Can you complete the task when you're looking through a straw. The asterix only approach is fine for visual + screen reader people, but will probably be a problem for low vision.

**Comment by nschonni** [comment] 2017-02-22 04:38
Oops PEBCAK, I realized my previous comment was intended for the conversation around the "optional vs. required in forms" so I'm deleting it and moving it there.

**Comment by neoinsight** [comment] 2017-02-23 18:19
@kodecount Close buttons lovely - looks like most are on left too, which addresses @nschonni low-vision issue as much as is possible. Certainly better than x in top corner for low vision!

**Comment by kodecount** [comment] 2017-02-23 18:23
Yes, hopefully the pull requests are accepted.

**Comment by kodecount** [comment] 2017-02-23 19:11
Thank You. Hopefully the pull requests are accepted. Either way gets some attraction on the issue.

Also I'm not sure how fimliar with HTML code you are but I made sure to have the same text as the other buttons, but for visual purposes only display 'Close'

```html
<button type="button" id="ftrClose" class="btn btn-sm btn-default pull-left overlay-close" style="" title="Close (escape key)">Close<span class="wb-inv">(escape key)</span></button>
```

The text in `<span class="wb-inv">...</span>` would only be read by screen reader.

**Closed** 2017-04-06 15:52 UTC
