### ISSUE TITLE
Dropdown Menus (Don't work without JS)

### ISSUE THREAD

**Issue by kodecount** [wet-boew/GCWeb#1218] opened 2017-01-19 18:39 UTC
As discussed over in https://github.com/wet-boew/wet-boew/issues/7847 menus aren't usable when JS is off or user is in wbdisable mode. This is actually a issue on [https://www.canada.ca/](https://www.canada.ca/).

**Comment by EricDunsworth** [comment] 2017-01-19 20:58
FYI this seems to be a duplicate of #1163.

**Closed** 2017-01-19 21:47 UTC
