### ISSUE TITLE
Keywords filter for departments & agencies page

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#953] opened 2015-03-04 20:05 UTC
Hi guys!  So, at some point we’ll have to get that keywords filter up and running on the departments and agencies landing page:  [http://wet-boew.github.io/themes-dist/GCWeb/dept-en.html] (http://wet-boew.github.io/themes-dist/GCWeb/dept-en.html)

Sounds like we’ll probably end up using some kind of implementation of the WET data tables plugin, which would be great.  Shawn has already gotten something like this going on the “find an office” table, here:  ~~[http://servicecanada.github.io/GCWeb/contact/office-en.html](http://servicecanada.github.io/GCWeb/contact/office-en.html)~~ 

This raises two questions:

1.  Will we be able to make some little adjustments to the way that table is presented?  In particular, we could improve it by moving that “filter items” field over to the left side, and combining it with the instructional text up above.  That way it could read more like “Enter the name of the institution you are looking for: ____________” keeping the instructions and the field tight together.

2.  Do we have any way to bolster each data record in the table with metadata that can be picked up by the filter/keyword mechanism?  That way, for example, a data record for the “Royal Canadian Mounted Police” could have the “RCMP” acronym hidden in metadata so that users who type RCMP into the filter field would see that record in the results, even in cases where the acronym doesn’t appear in the visible description.

Any thoughts on this?  I’d tag this issue with an “enhancement” or “question” label if I could, but I think my IE9 may be putting GitHub on crutches over here...

**Comment by LaurentGoderre** [comment] 2015-03-04 20:21
I am worried that using the datatable for this is going to causes some issues in the future.

**Comment by DK-TBS** [comment] 2015-03-04 21:35
I'm pretty sure that it was a datatable that @shawnthompson put to use on the "[find an office](http://servicecanada.github.io/GCWeb/contact/office-en.html)" page.  Do you forsee troubles with the way it's being used there, or are your concerns more around the departments/agencies page?

Personally, I don't have an opinion on exactly how it would be done, as long as we can get that little filter keyword thing running nicely.

**Comment by LaurentGoderre** [comment] 2015-03-04 21:50
Using an element for other purpose than what was intended is always risky.  I guess it can be used in the meantime but it probably would be safer to have a filter plugin that doesn't rely on tables.

**Comment by shawnthompson** [comment] 2015-03-04 21:53
And you're the right person to build it @LaurentGoderre. :stuck_out_tongue_closed_eyes: 

@masterbee is actually putting something together.

**Comment by DK-TBS** [comment] 2015-03-05 14:31
Ahh, okay I see your concern:  it's that the content there isn't really tabular data.  Agreed!

**Comment by hsrudnicki** [comment] 2015-05-05 20:55
@DK-TBS @LaurentGoderre @masterbee  @shawnthompson : Have you tackle this issue in order to close it?
Based on your discussion, the issue can be fixed by:
1) use of DataTable(s)
2) use of keyword-search/filter(s)

**Comment by pcwsmith** [comment] 2015-05-05 21:06
The key to this one is the filter functionality. We need to be able to extract that filter box out of the WET data table so that it can be run against other stuff - e.g. in the case of http://www.canada.ca/en/gov/dept/ the idea is basically to have the filter box run against a bunch of ULs.

**Comment by hsrudnicki** [comment] 2015-05-06 20:16
Just by occasion, the filtering functionality that is provided by DataTables may be useful, here is a simple example https://datatables.net/examples/api/multi_filter.html
In case of RESTFULL search approach, based on http://stackoverflow.com/questions/207477/restful-url-design-for-search, perfectly Restful in searching can be a use of querystrings, additionally see MS Search REST service in SharePoint Server 2013

**Comment by pcwsmith** [comment] 2015-05-06 20:24
@hsrudnicki oh I'm not saying not to keep it in the WET table. Absolutely needed there. It's just that we *also* need to be able to filter on other things too.

**Comment by hsrudnicki** [comment] 2015-05-06 20:40
@DK-TBS @LaurentGoderre @masterbee @shawnthompson @pcwsmith  : So you need more time for this issue to close it

**Comment by masterbee** [comment] 2015-05-06 20:46
@hsrudnicki  - Yes please this issue thread has some good intel and resource linkages. We will drum up something fairly soon to close this issue.

**Comment by hsrudnicki** [comment] 2015-05-07 14:35
https://github.com/wet-boew/wet-boew/issues/6748

**Comment by hsrudnicki** [comment] 2016-01-15 21:28
Based on last comment from @masterbee : Can be this issue closed or otherwise?

**Comment by shawnthompson** [comment] 2016-01-25 20:56
I've been talking to @masterbee about creating a filter plugin for lists and sections for WET.

Something like List.js. This would help in the search pages as well as the departments and agencies list. Hoping to make it flexible enough to use for sections.

**Comment by cfarquharson** [comment] 2016-01-25 21:00
@shawnthompson @masterbee Did you see this issue I raised last week.  Might be a solution for you. https://github.com/wet-boew/wet-boew/issues/7341 (if not, can you still implement that solution?)

**Comment by hsrudnicki** [comment] 2016-08-12 19:15
Can be this issue closed as fixed or otherwise? Please update this issue's status, thank you

**Comment by pcwsmith** [comment] 2016-08-15 17:30
since we're planning on going in a different direction with the depts. and agencies page, this issue can be closed

**Comment by hsrudnicki** [comment] 2016-08-16 21:17
Due to the above, this issue can be closed. Thank you

**Closed by hsrudnicki** 2016-08-16 21:17 UTC
